# This file was generated by GoReleaser. DO NOT EDIT.
cask "phpunit-parallel" do
  name "phpunit-parallel"
  desc "A CLI tool to run PHPUnit tests in parallel, with a beautiful terminal UI"
  homepage "https://github.com/alexdempster44/phpunit-parallel"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "phpunit-parallel"

  on_macos do
    on_intel do
      url "https://github.com/alexdempster44/phpunit-parallel/releases/download/v#{version}/phpunit-parallel_#{version}_darwin_amd64.tar.gz"
      sha256 "3bedd7dedbc5fec2babc25ccc630bb56e2873cea4afdf34fa9ad650964ecabf5"
    end
    on_arm do
      url "https://github.com/alexdempster44/phpunit-parallel/releases/download/v#{version}/phpunit-parallel_#{version}_darwin_arm64.tar.gz"
      sha256 "dcf4725bf9e02afd005b3dd156548b3d6881a71af334062cb754a33f7fb80cd1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexdempster44/phpunit-parallel/releases/download/v#{version}/phpunit-parallel_#{version}_linux_amd64.tar.gz"
      sha256 "bcee5de3625acb411cd697b385da8009e9b9441c63a577f831df5661af58b7da"
    end
    on_arm do
      url "https://github.com/alexdempster44/phpunit-parallel/releases/download/v#{version}/phpunit-parallel_#{version}_linux_arm64.tar.gz"
      sha256 "873ba9b3e9254d28fd795bc5f37c7a78031b2a66dd5b7170fe121b73e60297bd"
    end
  end

  # No zap stanza required
end
