# This file was generated by GoReleaser. DO NOT EDIT.
cask "pty-test" do
  version "0.1.0+1"

  on_macos do
    on_intel do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_darwin_amd64.tar.gz"
      sha256 "7114df87337a3d0527ccd98aaac9a7c9639c643894db93bf70bc8735ba44d04e"
    end
    on_arm do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_darwin_arm64.tar.gz"
      sha256 "7acc6d485f737218cedca8d3c9fc4e182c6232bd2928b0a8c27c41c4c6046912"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_linux_amd64.tar.gz"
      sha256 "9d32ddf10547ab2d293c6c995a640b89a666503e66f1b563bc2fc83b0e2b0d31"
    end
    on_arm do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_linux_arm64.tar.gz"
      sha256 "d914bdbea1eb622fcb8cb382952e87a428d42b5b759fcb0acd5454b6052c4f0e"
    end
  end

  name "pty-test"
  desc "An MCP server that lets an AI drive and inspect TUI apps through a real PTY"
  homepage "https://github.com/alexdempster44/pty-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pty-test"

  # No zap stanza required

end
