# This file was generated by GoReleaser. DO NOT EDIT.
cask "pty-test" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_darwin_amd64.tar.gz"
      sha256 "3a246ac888a0caa1af604b59e1d9b78ead16b0955aa8fa464f11c68cda121201"
    end
    on_arm do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_darwin_arm64.tar.gz"
      sha256 "b114c0161c00a61f9b820c02b67a99e83b8a43a6daac710619a5e44640b6491b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_linux_amd64.tar.gz"
      sha256 "5122af7e8af341cbf6f6fa75cef38885ac811c2760a7198470eca4f3c3ac66f4"
    end
    on_arm do
      url "https://github.com/alexdempster44/pty-test/releases/download/v#{version}/pty-test_#{version}_linux_arm64.tar.gz"
      sha256 "12f64888969031fe7685cfc58a2a130dd3dcb32274755fb63f6be95e4f2ba3ec"
    end
  end

  name "pty-test"
  desc "An MCP server that lets an AI drive and inspect TUI apps through a real PTY"
  homepage "https://github.com/alexdempster44/pty-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pty-test"

  # No zap stanza required

end
